### PR TITLE
Update SimpleTcpServer.cs

### PR DESCRIPTION
**Pull request by sector13371**
applied a fix for my own issue; https://github.com/jchristn/SimpleTcp/issues/83

### CODE REVIEW

**Comment by jchristn** [comment]
Thanks @sector13371 - merging now.  I'll also amend to include the other dictionaries where the entry may reside.  Strange I was unable to reproduce on my side, glad you caught it!

**Comment by jchristn** [comment]
The server ```DataReceiver``` method should have been responsible for removing from the dictionaries.  I think what might have been happening is ```DisconnectClient``` disposed the client object before the ```DataReceiver``` was able to complete.  

Would you mind giving v2.4.0.1 a try and letting me know if this still works as expected on your side?  It looks good on mine.

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.4.0.1
Commit: https://github.com/jchristn/SimpleTcp/commit/c1bd23e737c9e1379c91d75d40efb3c6dfc923fd

**Comment by sector13371** [comment]
I've tryed it, now it works as expected now i'm having no issues with latest version. Thanks for that great library again.

**Comment by jchristn** [comment]
Glad to hear. Thanks for finding the issue and letting me know, and also for your kind words!

**Pull request merged**
