### PR TITLE
Use events instead of callbacks

### LINKED ISSUE #9: Use events instead of callbacks
Is there any reason why this library is using `Func` callbacks instead of events? Events would be the idiomatic .NET tool for this job, and give a more pleasant dev experience.

Is it perhaps related to the callbacks returning `Task`, and that SimpleTcp must for some reason await callback completion? If so, why?

### PR DESCRIPTION
**Pull request by cmeeren**
Closes #9 

I know you said "next major version", so no hurry, I'd just like to help out and show how it can be done. (That said, of course I'd like this sooner rather than later 👍 ) )

At least I *think* this is correct. I've been working on F# for the last couple of years, so my C# skills are a bit rusty.

Please test; I tried the test projects, and things seem to be working just as well as they do on the current master, but I'm having some trouble with the test apps on master too (client times out some seconds after successfully connecting, and server doesn't send messages to client).

### CODE REVIEW

**Comment by jchristn** [comment]
Oh wow, thanks for producing this @cmeeren !  I had found some samples on how to do this and started a prototype and I will certainly lean on this when building it out!

**Comment by jchristn** [comment]
PR is super clean, thank you for that.

**Comment by cmeeren** [comment]
Happy to help! And don't feel you have to merge this PR; I'm happy as long as it's implemented, no matter whose name is on the commit.

**Comment by jchristn** [comment]
Thank you, I'll likely implement this as is and rev the version.

Out of curiosity (and for my own education, as this model will likely influence several other libraries I have out there) what is the benefit in this model vs using ```Func``` outside of A) expected pattern and B) the ability to hang multiple event handlers off of a single event?  

Thanks again for your help and guidance!

**Comment by cmeeren** [comment]
I think those are the main benefits, and certainly important ones (perhaps a bit unusual at first if you're coming from a non-.NET background, but vastly preferred in the .NET world over callbacks). Furthermore, the use of `EventArgs<T>` provides a backwards-compatible way to add new data to the event.

This page and the other pages in the menu may have more useful info: https://docs.microsoft.com/en-us/dotnet/standard/events/

Also, searching the web for ".NET event vs callback" is likely to yield some potentially helpful results.

**Comment by jchristn** [comment]
Hi @cmeeren, please let me know if this works for you!

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.0.1
Commit: https://github.com/jchristn/SimpleTcp/commit/b6aa2752dd3073656c9d55da351fac1f4ed11153 

Cheers,
Joel

**Pull request merged**
